bym-refitted/backyard-monsters-refitted

- client/scripts/SOUNDS.as
Apparently the game didn't save the state of the sound setting because of this one leftover line from testing by the OG devs.
This removes that line, and fixes the bug.
> Remove Leftover Code Muting the Game on Start - Bug Fix

- client/scripts/BUILDING11.as
- client/scripts/MAPROOM.as
- server/public/gamestage/assets/en.v8.json
Fixes a bug where opening the maproom just after placing it for the first time would crash the game.
> Add Check to Make Sure Maproom Finished Initializing (Crash Fix)

- server/src/controllers/base/save/handlers/purchaseHandler.ts
Store item expiry is expected to be epoch (seconds). It was being calculated as `currentTime (milliseconds) + duration (seconds)`.
This has been corrected.
> Fix: Store item expiry calculation

- client/scripts/BRESOURCE.as
Fixes the upgrade description for resource capacity:
```diff
- Capacity: Increases from 720 to 5,670
+ Capacity: Increases from 2,160 to 5,670
```
[Bug report](https://discord.com/channels/1126689848426774572/1302295995614363729)
> Fix resource capacity text

- client/scripts/BRESOURCE.as
The first value `#v1#` of the [upgrade description for resource buildings](https://github.com/bym-refitted/backyard-monsters-refitted/blob/d4e045a81306887dec3bdae006d30cc707825b31/server/public/gamestage/assets/english.json#L1588) is affected by the outpost modifier, but the second value `#v2#` isn't:
https://github.com/bym-refitted/backyard-monsters-refitted/blob/2a666de02d9b97e1812e02991edb620fc763e862/client/scripts/BRESOURCE.as#L308-L311
https://github.com/bym-refitted/backyard-monsters-refitted/blob/2a666de02d9b97e1812e02991edb620fc763e862/client/scripts/BRESOURCE.as#L232-L236
https://github.com/bym-refitted/backyard-monsters-refitted/blob/2a666de02d9b97e1812e02991edb620fc763e862/client/scripts/BRESOURCE.as#L295
This PR fixes the upgrade description in outposts by using the adjusted …
> Fix outpost resource production text

- server/src/controllers/base/load/balancedReward.ts
@React-1 just citing your message...
> Description:
>
>This fix will help reduce a lot of tickets, it has to do with user's not getting rewards at certain town hall levels, such as Korath, Krallen, >Diamond Spurtz Cannon.
>
>Details:
>
>These rewards are handled on the server, in the file balancedRewards.ts
>
>The issue comes from the fact that the script checks for the first key in the object being "0" since this building should always be the Town >Hall, and checks the "l" property on that object being the level of the Town Hall. If its above a certain level, insert the reward into the >database.
>
>The oversight was trusting the Backyard Monsters game client to always make sure the first building is the Town Hall. For some odd reason, the >people who report the issue, don't have a first …
> Bugfix - balancedReward 

- server/src/controllers/maproom/v2/cells/userCell.ts
Before it's 0 because the server don't return any value for `v` field, and client can't calculate it, so we just need return any number with minimum value of 1, so it can be calculated, here's takeover price of another player's outpost with only outpost building inside, so the empire value is 1
Before Fix:
After Fix:
Regular Kit empire value is 3,222,316, the takeover price is 8,750,000
Ultra Kit empire value is 41,526,414, the takeover price is 54,750,000.
> fix(takover-price): set price based on empire value

- client/scripts/com/monsters/maproom_advanced/MapRoomPopup.as
This is the same pull request as [PR #85](https://github.com/bym-refitted/backyard-monsters-refitted/pull/85), but I messed up the commits when attempting to squash them, so it was faster to make a new PR. 
This PR rewrites the GetCellsInRange function on the map room, which decides (like the name implies), given a center and a range, which cells are in range to attack. Kixeye's code had which cells were in range hardcoded for ranges 1 to 6, and then used a very obtuse algorithm to find 7 or more cells away from the center, summed with the fact that the code is already decompiled which difficulties reading even more. This was rewritten to calculate neighbors by first converting the hexagonal grid coordinates from the offset odd-q system to axial coordinates, making the calculations in …
> GetCellsInRange rewrite. 

- server/src/controllers/maproom/v2/cells/userCell.ts
when loading the map room and  there are multiple requests to `/worldmapv2/getarea`, some outpost doesn't showing the outpost level correctly (usually not happening in the first request).
to fix this, if the current cell is other player's outpost, we should populate User.save so we can calculate the level
Before fix:
After fix:
> fix(outpost-level): populate user with save for other user

- server/src/app.routes.ts
- server/src/controllers/base/save/baseSave.ts
- server/src/controllers/maproom/v2/getArea.ts
- server/src/controllers/maproom/v2/setMapVersion.ts
- server/src/middleware/auth.ts
This PR creates a guard on the `setMapVersion.ts` route to disable MapRoom access for users who's Discord account is less than 1 week old.
> Added validation for MapRoom access for account grace period

- server/src/controllers/base/load/modes/baseModeAttack.ts
- server/src/controllers/maproom/v2/cells/wildMonsterCell.ts
- server/src/models/worldmapcell.model.ts
- server/src/services/maproom/v2/validateRange.ts
- server/src/utils/worldIdtoNumber.ts
- In `wildMonsterCell.ts` the `baseid` is now generated using the current `worldid` as a number. This allows for multiple worlds to exist independently without identical `baseid` conflicts.
-  Flinger range validation was not taking into account the fact that the world wraps at the edges; for example, if a base is located at co-ordinate 0 x 0, then it cannot attack a cell at co-ordinate 1 x 799, as technically this is out of range.
- Additional cleanup, particularly in the `WorldMapCell` model, which sees the removal of optional constructor params, instead these are assigned directly before persisting to database.
- Slight performance improvements to the `worldidToNumber` converter.
<br>
- The way we are generating the current `baseid` (see wildMonsterCell.ts) and deriving the cellX and …
> baseid now factors in worldid | flinger range validation factors in toroidal map wrap-around

- server/src/controllers/base/save/baseSave.ts
- server/src/controllers/base/save/handlers/buildingDataHandler.ts
- server/src/controllers/base/save/zod/BaseSaveSchema.ts
- server/src/enums/SaveKeys.ts
- server/src/models/save.model.ts
This pull request improves how building data is handled throughout the game, particularly focusing on outposts and attack validation. These changes address issues with building construction timers resetting during outpost visits while also adding protection against potential exploits.
- Added Building Data Validation: Created a specialized handler that validates building data during save operations to prevent unauthorized removal of non-trap buildings
- Players can now build structures in outposts without timers resetting between attacks
- Prevents potential exploits where players might attempt to remove buildings during attacks
- Maintains expected gameplay by allowing trap removal (types 24 and 117) while protecting other structures
> Outposts now correctly persist building data with server-side validation

- client/scripts/BASE.as
- client/scripts/BFOUNDATION.as
Creating a pull request with the intent to resolve issue #135, along with a few other bugs I discovered that ended up being caused by similar issues. I have written down any relevant details regarding each change and the bugs' causes. Let me know if anything here seems wrong, needs clarification, or if you want anything done differently.
The following changes were made:
**BFOUNDATION.as:**  Added a check to `getBuildingSaveData` that excludes `GLOBAL._newBuilding` from being saved to a base's buildingData. This solves an issue where the Town Hall data was being overwritten, causing the game to replace it (Typically with a lower level one).
> Notes:
> - `GLOBAL._newBuilding` is a BFOUNDATION object that refers to the brand new building that the player is attempting to build from the …
> Bugfix: Townhall Up/Downgrading, Saving Unplaced Buildings, Mushrooms Canceling Worker

- client/scripts/ACADEMYPOPUP.as
There are only 8 total Inferno monsters that exist, but in ACADEMYPOPUP.as, the amount of inferno monsters is set to 9.
In the Inferno Academy screen, if you attempt to scroll past Spurtz (ID: “IC1”) or King Wormzor (ID: “IC8”) to the 9th slot, it will appear as though nothing happened and you must scroll again to go to the next monster. If you close and re-open the academy screen while on the 9th slot, this will cause the game to lock up due to an exception, as a monster with ID “IC9” does not exist.
This lock will also happen if you had Brain selected in the Overworld Academy, since Brain is in the 9th slot on the Overworld (ID: "C9") and the game remembers what slot you left you left the Academy screen on.
The following change was made to fix this issue:
**ACADEMYPOPUP.as:** When the …
> Bugfix: Infernal Academy can Cause Game to Lock.

- client/scripts/HATCHERYCCPOPUP.as
- client/scripts/HATCHERYPOPUP.as
- Stats bar width was incorrectly displayed for Balthazars.
- Inferno monsters incorrectly showed their cost in Goo.
---
- Unobfuscated all variables and removed unnecessary ones in `MonsterInfoB` for better readability.
- Changed the `speed` variable from `Integer` to `Number` (max speed can be `4.5 km/h`, using `Integer` caused the value to truncate to `4` which led to the display issue).
- Added conditional logic to display `Magma` or `Goo` depending on the monster's type.
---
If you don't have an `HCC`, this error wasn't present because `HATCHERYPOPUP` already uses `Number` for the `speed` variable.
- For inferno monsters it says Goo Cost XXX Magma Cost since that part is render in a different function.
> Fix Visuals Errors On  HATCHERYCCPOPUP.as

- client/scripts/BFOUNDATION.as
Fixes a clear oversight on my end. As I didn't properly analyze the condition comparison on line 2377. It was obviously not foolproof. 
This simple addition should fix any and all current and/or future issues we may have with the builders regarding how resources get selected and delegated to the animation function.
> Fix oversight where worker messes up upgrading anything that does not have a fortify property set

- client/scripts/BDECORATION.as
- client/scripts/INFERNOYARDPROPS.as
- client/scripts/OUTPOST_YARD_PROPS.as
- client/scripts/YARD_PROPS.as
This pull request is intended to resolve two issues regarding Decoration buildings.
1. Clicking and dragging the mouse while building a Decoration object can pause upgrades (typically Town Hall upgrades) due to an ID collision.
2. Players can gain an unlimited amount of golden DAVE statues by reloading their base, which does not appear to be intended behavior.
**BDECORATION.as:** Removed an erroneous `Constructed` function call from BDECORATION's `Place` function.
**Context:**
- BDECORATION objects extend the BFOUNDATION object.
- The `_id` of BFOUNDATION objects is only properly set once the building is fully placed in the yard.
- There is nothing specifically within BDECORATION that sets the building's `_id`.
- The `Constructed` function calls `QUEUE.Remove`, which removes the worker …
> Bugfix: Infinite DAVE Statues, Decorations Pausing Workers

- client/scripts/GLOBAL.as
- client/scripts/com/monsters/maproom_advanced/MapRoomPopup.as
- server/src/server.ts
It turns out the original developers did not account for a type of stage display mode when using the standalone Adobe Flash player, specifically on the Map Room window:
```ts
StageDisplayState.FULL_SCREEN_INTERACTIVE
```
Therefore, we now know that the Map Room did in fact have fullscreen capabilities in the original and it was not patched out by the devs, but instead forgotten.
The map can now enter and exit fullscreen mode:
> Fixed 'fullscreen' mode on Map Room 2 

- client/scripts/com/monsters/monsters/components/abilities/RezghulResurrectAttack.as
This pull request is intended to resolve the following issues related to Rezghul's resurrection ability:
- Rezghul resurrecting a defending monster during an attack causes the game to freeze.
- Rezghul can use their resurrection ability outside of an attacking state (most often while inside a housing).
All changes are client side. As always, let me know if anything here looks incorrect, needs clarification, or you would want done differently.
**RezghulResurrectAttack.as:** 
- Changed variable names for readability. 
- Modified function `getValidTargetsInRange` to not give any targets if the monster using this ability is not in a battle state (thus the ability can _only_ be used in a battle state).
- When a defending monster is resurrected, the function `findDefenseTargets` will be called …
> Bugfix: Rezghul using ability outside of battle state. Resurrecting defending monsters freezes game.

- client/scripts/ATTACK.as
- client/scripts/BASE.as
This pull request is intended to fix an issue where monsters can be spent before they are flung during an attack, and to fix a minor code oversight relating to attacks. All changes are client side.
As always, let me know if anything here looks incorrect, needs clarification, or you would want done differently.
**ATTACK.as:** Fixing an oversight where the variable denoting the total amount of creatures selected to be flung (`_creaturesLoaded`) does not decrement when deselecting a champion.
**Context:** 
- This variable (alongside `_creaturesFlung`) is currently only used for error checking in CREEPS.as to verify the amount of flung creatures matches the amount of your creatures that are alive in the attack. It has no effect on anything gameplay related.
- This variable does get …
> Bugfix: Monsters removed from housing before being flung. Minor oversight when deselecting champion.

- client/scripts/BASE.as
- client/scripts/GLOBAL.as
- client/scripts/com/monsters/monsters/components/abilities/AOEDamage.as
- client/scripts/com/monsters/monsters/creeps/inferno/KingWormzer.as
This pull request is intended to do the following:
- Resolves issue #136 
- Fixes an issue where the game could become stuck saving forever when a base saves right as the player hits the "go to next outpost" button.
- Changes King Wormzor's ability to no longer damage other monsters (still damages buildings).
- Fixes an issue where Bandito and Fink dealt damage to champions twice when their ability was unlocked.
All changes are client side. As always, let me know if anything here looks incorrect, needs clarification, or you would want done differently.
**BASE.as:** `m_yardType` is no longer set to "Outpost" prematurely when loading the player's next outpost.
**GLOBAL.as:** Will now wait until the current base is no longer saving before attempting to load the player's next base. …
> Bugfix: Champion Data Reset. AOEDamage Against Champions; King Wormzor Change.

- client/scripts/CREATURES.as
- client/scripts/com/monsters/monsters/MonsterBase.as
- client/scripts/com/monsters/monsters/creeps/CreepBase.as
- client/scripts/com/monsters/monsters/creeps/inferno/Balthazar.as
This pull request is intended to make the following changes to Balthazar to make them behave more as intended:
- Balthazar now actively targets Krallen like other champions.
- Balthazar can now be hit by any defense tower, including traps, ADTs, cannons, ect.
- Balthazar now has their intended x3 damage multiplier against monsters while defending from a compound/bunker.
All changes are client side. As always, let me know if anything here looks incorrect, needs clarification, or you would want done differently.
**CREATURES.as:** Added the `_hasLivingGuardian` function. Returns true if there is an active defending champion above 0 health.
The `tickBAttack` function in **CreepBase.as**, and the `findTarget` function in **MonsterBase.as** now use this function.
**MonsterBase.as:** Modified …
> Balthazar: Targeting Krallen, Defense Flags, Damage Multiplier when Defending.

- server/src/controllers/mail/getMessageThreads.ts
- server/src/controllers/mail/reportMessageThread.ts
- server/src/controllers/mail/sendMessage.ts
- server/src/database/migrations/Migration20250916000000.ts
- server/src/models/message.model.ts
- server/src/models/user.model.ts
This PR implements a comprehensive player blocking (ignore) system for the messaging/mailbox functionality, allowing users to block other players and prevent unwanted communication.
- Players can block other users through the mailbox interface
- Blocked users are stored in a JSON array on the User model
- Blocking is initiated via the existing "Report Player" button with reason "block"
- **Mailbox View**: Threads with blocked users are completely hidden from the mailbox
- **Message Sending**: Blocked users cannot send messages to users who blocked them
- **Bidirectional Prevention**: Users cannot send messages to players they have blocked
- Leverages existing ActionScript client logic (`reportid > 0` check)
- No client-side changes required - works with current UI
- Maintains backward …
> Implemented block player functionality for Mailbox
